version: '3.8'

services:
  app:
    image: frantzme/ballerina:lite #frantzme/pythondev:lite #frantzme/rustpy:lite

    volumes:
      - ..:/sync:cached  

    # Overrides default command so things don't shut down after the process ends.
    command: sh -c "chmod 777 .devcontainer/vs_startup.sh && ./.devcontainer/vs_startup.sh && sleep infinity"

