name: Ballerina Packaging and Uploading

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install SDK and Graalvm
        if: false
        run: curl -s "https://get.sdkman.io" | bash && source "$HOME/.sdkman/bin/sdkman-init.sh" && yes|sdk i java 23-graalce

      - name: Show
        if: false
        run: ls -altr $HOME/.sdkman/candidates/ballerina

      - name: Main Executing
        if: false
        run: GRAALVM_HOME=HOME/.sdkman/candidates/java/23-graalce $HOME/.sdkman/candidates/ballerina/current/bin/ballerina build --graalvm

      - name: Main Executing
        if: false 
        run: bal build --graalvm

      - name: Build the docker image
        run: docker run -v `pwd`:/sync/ --workdir /sync/ frantzme/ballerina:lite bal build --graalvm
