name: Ballerina Packaging and Uploading

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build the docker image
        run: docker run -v `pwd`:/sync/ --workdir /sync/ frantzme/ballerina:lite bal build --graalvm

      - name: Ballerina Push
        if: false
        uses: ballerina-platform/ballerina-action@master
        with:
          args: 
            push 
        env: 
            BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BallerinaToken }}